dist:
  module: github.com/upcloud-community/opentelemetry-upcloud-receiver/collector
  name: otelcol-upcloud
  description: OpenTelemetry Collector distribution with UpCloud receiver
  output_path: ./_build
  otelcol_version: 0.146.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.146.1
  - gomod: github.com/upcloud-community/opentelemetry-upcloud-receiver v0.0.0
    import: github.com/upcloud-community/opentelemetry-upcloud-receiver/receiver/upcloudreceiver
    name: upcloudreceiver
    path: ./

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.146.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.146.1

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.52.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.52.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.52.0
